import test from 'node:test';
import assert from 'node:assert/strict';
import {
  sanitizeClaudeText,
  sanitizeToClaudeError,
  buildClaudeSystemPrompt,
  getClaudeModelName,
  AUTONOMOUS_AGENT_PROTOCOL,
  AUTONOMOUS_SOFTWARE_ENGINEERING_AGENT_EXECUTION_PROTOCOL,
  ProxyService
} from '../src/services/ProxyService.js';
import { createProxyRouter } from '../src/routes/proxyRoutes.js';
import { Account } from '../src/core/Account.js';
import { AccountPool } from '../src/services/AccountPool.js';
import { JsonStorage } from '../src/storage/JsonStorage.js';
import { AppConfig } from '../src/config.js';

class MockResponse {
  constructor() {
    this.statusCode = 200;
    this.headers = {};
    this.body = null;
    this.chunks = [];
    this.ended = false;
    this.headersSent = false;
  }

  status(code) {
    this.statusCode = code;
    return this;
  }

  setHeader(name, value) {
    this.headers[name.toLowerCase()] = value;
    this.headersSent = true;
    return this;
  }

  json(data) {
    this.body = data;
    this.ended = true;
    return this;
  }

  send(data) {
    this.body = data;
    this.ended = true;
    return this;
  }

  write(chunk) {
    this.headersSent = true;
    this.chunks.push(chunk);
    return true;
  }

  end() {
    this.ended = true;
    return this;
  }
}

test('Claude mask utilities replace Grok brand with Claude', () => {
  const cleaned = sanitizeClaudeText('Generated by Grok-4.6 from xAI on x.ai');
  assert.equal(cleaned, 'Generated by Claude Sonnet 5 from Anthropic on anthropic.com');

  const emptyClean = sanitizeClaudeText(null);
  assert.equal(emptyClean, null);

  const prompt = buildClaudeSystemPrompt('Claude Sonnet 5');
  assert.ok(prompt.includes('Claude Sonnet 5'));
  assert.ok(prompt.includes('Anthropic'));
  assert.ok(!prompt.includes('Grok-4.6'));

  assert.equal(getClaudeModelName('claude-3-5-sonnet-20241022'), 'Claude Sonnet 5');
  assert.equal(getClaudeModelName('claude-3-opus-20240229'), 'Claude Opus 5');
  assert.equal(getClaudeModelName('claude-3-5-haiku-20241022'), 'Claude Haiku 4.5');
  assert.equal(getClaudeModelName('claude-fable'), 'Claude Fable 5');
  assert.equal(getClaudeModelName('custom-unknown'), 'Claude Sonnet 5');

  const errorSanitized = sanitizeToClaudeError('grok-4.6 failed on cli-chat-proxy.grok.com from xai');
  assert.ok(errorSanitized.includes('claude-3-5-sonnet'));
  assert.ok(errorSanitized.includes('api.anthropic.com'));
  assert.ok(errorSanitized.includes('Anthropic'));

  assert.ok(AUTONOMOUS_AGENT_PROTOCOL.includes('AUTONOMOUS SOFTWARE ENGINEERING AGENT EXECUTION PROTOCOL'));
  assert.equal(AUTONOMOUS_SOFTWARE_ENGINEERING_AGENT_EXECUTION_PROTOCOL, AUTONOMOUS_AGENT_PROTOCOL);
});

test('ProxyService handleChatCompletion non-streaming translates and records usage', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  const acc = await pool.addAccount({ email: 'grok1@test.com', ssoToken: 'sso-tok-1' });

  const proxy = new ProxyService(pool, config);

  const originalFetch = globalThis.fetch;
  let requestedUrl = null;
  let requestedBody = null;
  let requestedHeaders = null;

  globalThis.fetch = async (url, options) => {
    requestedUrl = url;
    requestedBody = JSON.parse(options.body);
    requestedHeaders = options.headers;
    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'application/json' }),
      json: async () => ({
        id: 'chatcmpl-mock-1',
        choices: [{ message: { role: 'assistant', content: 'Hello from Grok-4.6 at xAI!' } }],
        usage: { total_tokens: 42 }
      })
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleChatCompletion({
      model: 'claude-3-5-sonnet',
      messages: [{ role: 'user', content: 'Hi' }]
    }, res);

    assert.equal(res.statusCode, 200);
    assert.equal(requestedUrl, `${config.GROK_PROXY_BASE}/chat/completions`);
    assert.equal(requestedBody.model, 'grok-4.6');
    assert.ok(requestedBody.messages[0].content.includes('Claude Sonnet 5'));
    assert.equal(requestedHeaders['Authorization'], 'Bearer sso-tok-1');

    assert.equal(res.body.choices[0].message.content, 'Hello from Claude Sonnet 5 at Anthropic!');
    assert.equal(acc.requestCount, 1);
    assert.equal(acc.totalTokens, 42);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService handleChatCompletion 429 failover to next account', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  const acc1 = await pool.addAccount({ email: 'acc1@test.com', ssoToken: 'tok1' });
  const acc2 = await pool.addAccount({ email: 'acc2@test.com', ssoToken: 'tok2' });

  const proxy = new ProxyService(pool, config);

  const originalFetch = globalThis.fetch;
  const attempts = [];

  globalThis.fetch = async (url, options) => {
    const auth = options.headers['Authorization'];
    attempts.push(auth);

    if (auth === 'Bearer tok1') {
      return {
        ok: false,
        status: 429,
        headers: new Headers({ 'retry-after': '60' }),
        text: async () => 'Rate limit exceeded'
      };
    }

    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'application/json' }),
      json: async () => ({
        id: 'chatcmpl-mock-2',
        choices: [{ message: { role: 'assistant', content: 'Success from acc2' } }],
        usage: { total_tokens: 15 }
      })
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleChatCompletion({
      model: 'grok-4.6',
      messages: [{ role: 'user', content: 'Test failover' }]
    }, res);

    assert.equal(res.statusCode, 200);
    assert.deepEqual(attempts, ['Bearer tok1', 'Bearer tok2']);
    assert.equal(acc1.status, 'cooling');
    assert.ok(acc1.cooldownUntil > Date.now());
    assert.equal(acc2.requestCount, 1);
    assert.equal(res.body.choices[0].message.content, 'Success from acc2');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService handleAnthropicMessages translates request, injects protocol, and returns Claude format', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  await pool.addAccount({ email: 'anthropic-acc@test.com', ssoToken: 'tok-claude' });

  const proxy = new ProxyService(pool, config);

  const originalFetch = globalThis.fetch;
  let capturedBody = null;

  globalThis.fetch = async (url, options) => {
    capturedBody = JSON.parse(options.body);
    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'application/json' }),
      json: async () => ({
        id: 'chatcmpl-tool-mock',
        choices: [{
          message: {
            role: 'assistant',
            content: 'I will inspect the files.',
            tool_calls: [{
              id: 'call_123',
              type: 'function',
              function: {
                name: 'view_file',
                arguments: '{"path":"src/app.js"}'
              }
            }]
          },
          finish_reason: 'tool_calls'
        }],
        usage: { prompt_tokens: 100, completion_tokens: 30, total_tokens: 130 }
      })
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleAnthropicMessages({
      model: 'claude-3-5-sonnet-20241022',
      system: 'You are an assistant.',
      messages: [
        { role: 'user', content: 'Check src/app.js' }
      ],
      tools: [
        {
          name: 'view_file',
          description: 'View file contents',
          input_schema: { type: 'object', properties: { path: { type: 'string' } } }
        }
      ]
    }, res);

    assert.equal(res.statusCode, 200);
    assert.equal(capturedBody.model, 'grok-4.6');
    assert.ok(capturedBody.tools.length > 0);
    assert.equal(capturedBody.tools[0].function.name, 'view_file');

    // System message should contain Claude persona and AUTONOMOUS PROTOCOL
    const sysMsg = capturedBody.messages.find(m => m.role === 'system');
    assert.ok(sysMsg.content.includes('Claude Sonnet 5'));
    assert.ok(sysMsg.content.includes('AUTONOMOUS SOFTWARE ENGINEERING AGENT EXECUTION PROTOCOL'));

    // Anthropic response format
    assert.equal(res.body.type, 'message');
    assert.equal(res.body.role, 'assistant');
    assert.equal(res.body.model, 'claude-3-5-sonnet-20241022');
    assert.equal(res.body.stop_reason, 'tool_use');
    assert.equal(res.body.content.length, 2);
    assert.equal(res.body.content[0].type, 'text');
    assert.equal(res.body.content[0].text, 'I will inspect the files.');
    assert.equal(res.body.content[1].type, 'tool_use');
    assert.equal(res.body.content[1].id, 'call_123');
    assert.deepEqual(res.body.content[1].input, { path: 'src/app.js' });
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService handleAnthropicMessages SSE streaming pipes correctly', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  await pool.addAccount({ email: 'stream@test.com', ssoToken: 'tok-stream' });

  const proxy = new ProxyService(pool, config);

  const sseChunks = [
    'data: {"choices":[{"delta":{"content":"Hello "}}]}\n\n',
    'data: {"choices":[{"delta":{"content":"world!"}}]}\n\n',
    'data: [DONE]\n\n'
  ];

  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => {
    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'text/event-stream' }),
      body: (async function* () {
        for (const chunk of sseChunks) {
          yield new TextEncoder().encode(chunk);
        }
      })()
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleAnthropicMessages({
      model: 'claude-3-5-sonnet-20241022',
      messages: [{ role: 'user', content: 'Say hello' }],
      stream: true
    }, res);

    assert.equal(res.headers['content-type'], 'text/event-stream');
    const fullStream = res.chunks.join('');
    assert.ok(fullStream.includes('event: message_start'));
    assert.ok(fullStream.includes('event: content_block_start'));
    assert.ok(fullStream.includes('event: content_block_delta'));
    assert.ok(fullStream.includes('"text_delta"'));
    assert.ok(fullStream.includes('Hello '));
    assert.ok(fullStream.includes('world!'));
    assert.ok(fullStream.includes('event: message_stop'));
    assert.equal(res.ended, true);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService returns 429 when all accounts in pool are cooling', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  const acc = await pool.addAccount({ email: 'cooled@test.com', ssoToken: 'cooled-tok' });
  await pool.markCooling(acc.id, 600000);

  const proxy = new ProxyService(pool, config);

  const resClaude = new MockResponse();
  await proxy.handleAnthropicMessages({ messages: [] }, resClaude);
  assert.equal(resClaude.statusCode, 429);
  assert.equal(resClaude.body.error.type, 'rate_limit_error');

  const resOpenAI = new MockResponse();
  await proxy.handleChatCompletion({ messages: [] }, resOpenAI);
  assert.equal(resOpenAI.statusCode, 429);
  assert.equal(resOpenAI.body.error.type, 'rate_limit_error');
});

test('createProxyRouter mounts /v1/messages, /messages, /v1/chat/completions, and /v1/models', () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  const proxy = new ProxyService(pool, config);

  const router = createProxyRouter(proxy);
  assert.ok(router);

  const routes = router.stack
    .filter(layer => layer.route)
    .map(layer => ({
      path: layer.route.path,
      methods: Object.keys(layer.route.methods)
    }));

  const paths = routes.map(r => r.path);
  assert.ok(paths.includes('/v1/messages'));
  assert.ok(paths.includes('/messages'));
  assert.ok(paths.includes('/v1/chat/completions'));
  assert.ok(paths.includes('/v1/models'));
});

test('ProxyService handleAnthropicMessages streams tool call deltas correctly', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  await pool.addAccount({ email: 'toolstream@test.com', ssoToken: 'tok-tc-stream' });

  const proxy = new ProxyService(pool, config);

  const sseChunks = [
    'data: {"choices":[{"delta":{"tool_calls":[{"index":0,"id":"call_abc","function":{"name":"write_file","arguments":"{\\"path\\""}}]}}]}\n\n',
    'data: {"choices":[{"delta":{"tool_calls":[{"index":0,"function":{"arguments":":\\"a.txt\\"}"}}]}}]}\n\n',
    'data: [DONE]\n\n'
  ];

  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => {
    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'text/event-stream' }),
      body: (async function* () {
        for (const chunk of sseChunks) {
          yield new TextEncoder().encode(chunk);
        }
      })()
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleAnthropicMessages({
      model: 'claude-3-5-sonnet-20241022',
      messages: [{ role: 'user', content: 'Create file a.txt' }],
      stream: true
    }, res);

    const fullStream = res.chunks.join('');
    assert.ok(fullStream.includes('event: content_block_start'));
    assert.ok(fullStream.includes('"tool_use"'));
    assert.ok(fullStream.includes('"name":"write_file"'));
    assert.ok(fullStream.includes('"input_json_delta"'));
    assert.ok(fullStream.includes('stop_reason":"tool_use"'));
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService handleAnthropicMessages recovers from 401 and upstream errors', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  const acc1 = await pool.addAccount({ email: 'auth-fail@test.com', ssoToken: 'tok-bad' });
  const acc2 = await pool.addAccount({ email: 'auth-ok@test.com', ssoToken: 'tok-good' });

  const proxy = new ProxyService(pool, config);

  const originalFetch = globalThis.fetch;
  let attempt = 0;

  globalThis.fetch = async (url, options) => {
    attempt++;
    if (attempt === 1) {
      return {
        ok: false,
        status: 401,
        text: async () => 'Unauthorized token'
      };
    }
    return {
      ok: true,
      status: 200,
      headers: new Headers({ 'content-type': 'application/json' }),
      json: async () => ({
        id: 'chatcmpl-ok',
        choices: [{ message: { role: 'assistant', content: 'Recovered after 401' } }],
        usage: { total_tokens: 20 }
      })
    };
  };

  try {
    const res = new MockResponse();
    await proxy.handleAnthropicMessages({ messages: [{ role: 'user', content: 'test' }] }, res);
    assert.equal(res.statusCode, 200);
    assert.equal(acc1.expiresAt, 0);
    assert.equal(res.body.content[0].text, 'Recovered after 401');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('ProxyService forwardChatCompletion and listModels work correctly', async () => {
  const config = new AppConfig();
  const pool = new AccountPool(new JsonStorage(), config);
  await pool.addAccount({ email: 'forward@test.com', ssoToken: 'tok-fwd' });
  const proxy = new ProxyService(pool, config);

  const resModels = new MockResponse();
  proxy.listModels({}, resModels);
  assert.equal(resModels.statusCode, 200);
  assert.ok(Array.isArray(resModels.body.data));
  assert.ok(resModels.body.data.some(m => m.id === 'grok-4.6'));

  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => ({
    ok: true,
    status: 200,
    headers: new Headers({ 'content-type': 'application/json' }),
    json: async () => ({ choices: [{ message: { content: 'test' } }] })
  });

  try {
    const resChat = new MockResponse();
    await proxy.forwardChatCompletion({ messages: [] }, resChat);
    assert.equal(resChat.statusCode, 200);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

